# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on:  windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
          dotnet build --no-restore src/HardwareExporterWindows/HardwareExporterWindows.csproj
          dotnet build --no-restore test/HardwareExporterWindows.Tests/HardwareExporterWindows.Tests.csproj
          dotnet build --no-restore src/HardwareExporterWeb/HardwareExporterWeb.csproj
          dotnet build --no-restore test/HardwareExporterWeb.Tests/HardwareExporterWeb.Tests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
          dotnet publish -r win-x64 --self-contained -p:PublishSingleFile=true -o bin/publish/HardwareExporterWindows  src/HardwareExporterWindows/HardwareExporterWindows.csproj
          dotnet publish -r win-x64 --self-contained -p:PublishSingleFile=true -o bin/publish/HardwareExporterWeb  src/HardwareExporterWeb/HardwareExporterWeb.csproj
    - name: Archive
      run: |
          Compress-Archive -Path bin/publish/HardwareExporterWeb -DestinationPath web.zip
          Compress-Archive -Path bin/publish/HardwareExporterWindows -DestinationPath exporter.zip
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: publish_file
        path: |
          web.zip
          exporter.zip
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          $TagName = $env:GITHUB_REF -replace 'refs/tags/', ''
          Get-ChildItem -Path ./ -Include @('publish.zip') | Foreach-Object {gh release upload $TagName $_}
          make push-all
